version: "3.9"
services:
  cc-stat3:
    container_name: cc-stat3 
    network_mode: host
    restart: always
    image: ccharbor.yuntongxun.com/aicc/cc-stat3:release_2025.3.3.3-36135df5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /app/volumes/licenses:/app/licenses
      - /app/logs/cc-stat3:/app/logs/cc-stat3
    environment:
      - APP_NAME=cc-stat3
      - CONFIG_ACTIVE=nacos
      - NACOS_CENTERS=10.1.106.93:8848
      - NACOS_NAMESPACE=cc_namespace
      - SPRING_CLOUD_NACOS_USERNAME=ENC(Dks5mOVb6ZWk44M2PXfj/w==)
      - SPRING_CLOUD_NACOS_PASSWORD=ENC(Dks5mOVb6ZWk44M2PXfj/w==)
      - SERVER_PORT=9110
      - JAVA_MEM=-Xms256M -Xmx1024M
      - LOG_PATH=/app/logs
      - TZ=Asia/Shanghai
      - SITE_CODE=3201
      - CONTAINER_TYPE=tomcat
      - LIC_PATH=/app/licenses/tongweb-license.dat
